### ISSUE TITLE
Ora3-V10.0.2-Error with Buff sorting of Food/Flasks-Still not fixed in an actual Raid of 10+ people

### ISSUE THREAD

**Issue by greenstones** [BigWigsMods/oRA3#122] opened 2022-11-15 04:49 UTC
## Describe the problem
I have reported this error before - if you click on flasks or food in the checks window in a raid, (must have at least 10+ members) you will get an error.  This is the second time you have claimed this error is fixed but isn't someone isn't testing the solution properly.

### What steps will reproduce the problem?

1.  Join a raid - not a party - not a 5 man - not solo - an actual raid - use LFR if you want - must have at least 10+ people, if you don't get the error at 10 keep adding people until it pops up, you can easily see it in an LFR or World Boss kill of 10+ people.
2.  Go to the check buffs panel click on FOOD or FLASK title, error will pop up.
3.  Error occurs because the sort routine is broken, is getting wrong variables.

### Consider attaching a screenshot below to help describe your issue (Attach directly, do not link to other websites)
![image](https://user-images.githubusercontent.com/42426983/201828908-147a8c3a-c4e8-4d74-8b82-2d9c769dc605.png)

### What version of the addon are you using? (Stating 'latest' is not useful)
ORA3-v10.0.2.zip

### Do you have an error log of what happened?
14x Interface/AddOns/oRA3/oRA3.lua:1177: attempt to compare string with number
[string "@Interface/AddOns/oRA3/oRA3.lua"]:1177: in function <Interface/AddOns/oRA3/oRA3.lua:1177>
[string "=[C]"]: in function `sort'
[string "@Interface/AddOns/oRA3/oRA3.lua"]:1185: in function <Interface/AddOns/oRA3/oRA3.lua:1179>

Locals:
a = <table> {
 1 = "Kiato"
 2 = 20
 3 = "|cffff2020No|r"
 4 = "|cff20ff20Yes|r"
 5 = "|cffff2020No|r"
 6 = "2/3"
}
b = <table> {
 1 = "Charredstone"
 2 = 30
 3 = 70
 4 = "|cffff2020No|r"
 5 = "|cffff2020No|r"
 6 = "3/3"
}
(*temporary) = 70
(*temporary) = "|cffff2020No|r"
(*temporary) = "attempt to compare string with number"
sortIndex = 3

### Any additional information? (example: WoW language if not English)
If you can't reproduce the error let me know and I will make a video of it in raid.

**Comment by funkydude** [comment] 2022-11-15 04:54
Duplicate of #119

No need to open new tickets.

**Closed by funkydude** 2022-11-15 04:54 UTC
Labels: retail

**Comment by greenstones** [comment] 2022-11-15 05:04
https://imgur.com/tQVukM6
